apiVersion: v1
kind: Secret
metadata:
  name: zybach-api-secrets
type: Opaque
stringData:
  zybachApiSecrets: |
    {
      "DB_CONNECTION_STRING": "Data Source={{ .Values.global.env.dbServer }};Initial Catalog={{ .Values.global.env.databaseName }};Persist Security Info=True;User ID={{ .Values.global.env.sqlUsername }};Password={{ .Values.global.secrets.apiSqlPassword }}",
      "HangfireUserName": "HangfireAdmin",
      "HangfirePassword": "{{ .Values.global.secrets.hangfirePassword }}",
      "SendGridApiKey": "{{ .Values.global.secrets.sendGridApiKey }}",
      "APPINSIGHTS_INSTRUMENTATIONKEY": "{{ .Values.global.env.appInsightsInstrumentationKey }}" 
      "AGHUB_API_KEY": "{{ .Values.global.secrets.agHubApiKey }}",
      "GEOOPTIX_API_KEY": "{{ .Values.global.secrets.geoOptixApiKey }}",
      "GET_API_SUBSCRIPTION_KEY": "{{ .Values.global.secrets.getApiSubscriptionKey }}",
      "INFLUXDB_TOKEN": "{{ .Values.global.secrets.influxDBToken }}",
      "OPENET_API_KEY": "{{ .Values.global.secrets.openETApiKey }}",
    }