exec sp_rename 'dbo.PK_AgHubWell_AgHubWellID', 'PK_Well_WellID', 'OBJECT';
exec sp_rename 'dbo.PK_AgHubWellIrrigatedAcre_AgHubWellIrrigatedAcreID', 'PK_WellIrrigatedAcre_WellIrrigatedAcreID', 'OBJECT';
exec sp_rename 'dbo.AK_AgHubWellIrrigatedAcre_AgHubWellID_IrrigationYear', 'AK_WellIrrigatedAcre_WellID_IrrigationYear', 'OBJECT';
exec sp_rename 'dbo.FK_AgHubWellIrrigatedAcre_AgHubWell_AgHubWellID', 'FK_WellIrrigatedAcre_Well_WellID', 'OBJECT';
exec sp_rename 'dbo.PK_AgHubWellStaging_AgHubWellStagingID', 'PK_WellStaging_WellStagingID', 'OBJECT';
exec sp_rename 'dbo.PK_AgHubWellIrrigatedAcreStaging_AgHubWellIrrigatedAcreStagingID', 'PK_WellIrrigatedAcreStaging_WellIrrigatedAcreStagingID', 'OBJECT';
exec sp_rename 'dbo.FK_AghubWell_StreamFlowZone_StreamFlowZoneID', 'FK_Well_StreamFlowZone_StreamFlowZoneID', 'OBJECT';
exec sp_rename 'dbo.AgHubWell.AgHubWellID', 'WellID', 'COLUMN';
exec sp_rename 'dbo.AgHubWellIrrigatedAcre.AgHubWellIrrigatedAcreID', 'WellIrrigatedAcreID', 'COLUMN';
exec sp_rename 'dbo.AgHubWellIrrigatedAcre.AgHubWellID', 'WellID', 'COLUMN';
exec sp_rename 'dbo.AgHubWellStaging.AgHubWellStagingID', 'WellStagingID', 'COLUMN';
exec sp_rename 'dbo.AgHubWellIrrigatedAcreStaging.AgHubWellIrrigatedAcreStagingID', 'WellIrrigatedAcreStagingID', 'COLUMN';
exec sp_rename 'dbo.AgHubWell', 'Well';
exec sp_rename 'dbo.AgHubWellIrrigatedAcre', 'WellIrrigatedAcre';
exec sp_rename 'dbo.AgHubWellStaging', 'WellStaging';
exec sp_rename 'dbo.AgHubWellIrrigatedAcreStaging', 'WellIrrigatedAcreStaging';