create table dbo.ChemicalFormulation
(
	ChemicalFormulationID int not null identity(1,1) constraint PK_ChemicalFormulation_ChemicalFormulationID primary key,
	ChemicalFormulationName varchar(100) constraint AK_ChemicalFormulation_ChemicalFormulationName unique,
	ChemicalFormulationDisplayName varchar(100) constraint AK_ChemicalFormulation_ChemicalFormulationDisplayName unique
)

create table dbo.ChemicalUnit
(
	ChemicalUnitID int not null constraint PK_ChemicalUnit_ChemicalUnitID primary key,
	ChemicalUnitName varchar(100) constraint AK_ChemicalUnit_ChemicalUnitName unique,
	ChemicalUnitPluralName varchar(100) constraint AK_ChemicalUnit_ChemicalUnitPluralName unique,
	ChemicalUnitLowercaseShortName varchar(100) constraint AK_ChemicalUnit_ChemicalUnitLowercaseShortName unique
)

create table dbo.ChemigationPermitAnnualRecordChemicalFormulation
(
	ChemigationPermitAnnualRecordChemicalFormulationID int not null identity(1,1) constraint PK_ChemigationPermitAnnualRecordChemicalFormulation_ChemigationPermitAnnualRecordChemicalFormulationID primary key,
	ChemigationPermitAnnualRecordID int not null constraint FK_ChemigationPermitAnnualRecordChemicalFormulation_ChemigationPermitAnnualRecord_ChemigationPermitAnnualRecordID foreign key references dbo.ChemigationPermitAnnualRecord(ChemigationPermitAnnualRecordID),
	ChemicalFormulationID int not null constraint FK_ChemigationPermitAnnualRecordChemicalFormulation_ChemicalFormulation_ChemicalFormulationID foreign key references dbo.ChemicalFormulation(ChemicalFormulationID),
	ChemicalUnitID int not null constraint FK_ChemigationPermitAnnualRecordChemicalFormulation_ChemicalUnit_ChemicalUnitID foreign key references dbo.ChemicalUnit(ChemicalUnitID),
	TotalApplied float not null,
	constraint AK_ChemigationPermitAnnualRecordChemicalFormulation_ChemigationPermitAnnualRecordID_ChemicalFormulationID_ChemicalUnitID unique (ChemigationPermitAnnualRecordID, ChemicalFormulationID, ChemicalUnitID)
)
GO

insert into dbo.ChemicalFormulation(ChemicalFormulationName, ChemicalFormulationDisplayName)
values
('0-0-12', '0-0-12'),
('0-0-25-175', '0-0-25-175'),
('0-0-25-17S', '0-0-25-17S'),
('10-0-0-26', '10-0-0-26'),
('10-34-0', '10-34-0'),
('12-0-0-24S', '12-0-0-24S'),
('12-0-0-26', '12-0-0-26'),
('12-0-0-26S', '12-0-0-26S'),
('20-10-2_5-2_5-2_5', '20-10-2.5-2.5-2.5'),
('22-0-0-13', '22-0-0-13'),
('22-0-3-3', '22-0-3-3'),
('24-0-0-10', '24-0-0-10'),
('2-5-0_2-drammatice', '2-5-0.2 DRAMMATIC E'),
('25-0-0-5', '25-0-0-5'),
('2-5-1-drammatick', '2-5-1 DRAMMATIC K'),
('25-3-0-0', '25-3-0-0'),
('26-0-0-4', '26-0-0-4'),
('26-0-0-5', '26-0-0-5'),
('26-0-2-2', '26-0-2-2'),
('26-0-3-3', '26-0-3-3'),
('26-0-3-5', '26-0-3-5'),
('26-0-3-5-_3', '26-0-3-5-.3'),
('27-0-0-5', '27-0-0-5'),
('28-0-0', '28-0-0'),
('28-0-0-4', '28-0-0-4'),
('28-0-0-5', '28-0-0-5'),
('28-0-6', '28-0-6'),
('30-0-0-13', '30-0-0-13'),
('30-0-0-2', '30-0-0-2'),
('30-0-0-3-0', '30-0-0-3-0'),
('30-0-0-4', '30-0-0-4'),
('31-0-0-1', '31-0-0-1'),
('32-0-0', '32-0-0'),
('32-0-0-3-0', '32-0-0-3-0'),
('34-0-0', '34-0-0'),
('46-0-0', '46-0-0'),
('8-20-5-5_5', '8-20-5-5.5'),
('9-27-25-2_5-2_5', '9-27-25-2.5-2.5')

insert into dbo.ChemicalFormulation(ChemicalFormulationName, ChemicalFormulationDisplayName)
values
('a-frame', 'A Frame'),
('alpine', 'Alpine'),
('approach', 'Approach'),
('aquila-xl', 'Aquila XL'),
('asana', 'Asana'),
('attain', 'Attain'),
('avicta-fungicide', 'Avicta Fungicide'),
('azoxy', 'Azoxy'),
('bifenthrin', 'Bifenthrin'),
('boron', 'Boron'),
('brawl', 'Brawl'),
('brigade', 'Brigade'),
('bumper', 'Bumper'),
('buncha-bugs', 'Buncha Bugs'),
('capture', 'Capture'),
('ch20-sureflow', 'CH20 Sure Flow'),
('chateau', 'Chateau'),
('chlorine', 'Chlorine'),
('copron-s', 'Copron S'),
('cover-xl', 'Cover XL'),
('dimethoate', 'Dimethoate'),
('eptam-7e', 'Eptam 7E'),
('fanfare', 'Fanfare'),
('firestone', 'Firestone'),
('forty-rock', 'Forty Rock'),
('frenzy-veloz', 'Frenzy Veloz'),
('fungicide', 'Fungicide'),
('govern', 'Govern'),
('grizzly-2', 'Grizzly 2'),
('headline', 'Headline'),
('hero', 'Hero'),
('hydra-hume001', 'Hydra-Hume 001'),
('k-row23', 'K-Row 23'),
('kts', 'KTS'),
('kugler', 'Kugler'),
('lamdacy', 'Lamdacy'),
('linex-4l', 'Linex 4L'),
('lorsban', 'Lorsban'),
('mustang-max', 'Mustang Max'),
('nanocal', 'Nanocal'),
('nitrogen', 'Nitrogen'),
('n-phuric-acid', 'N-Phuric Acid'),
('nutrisphere-n', 'Nutrisphere-N'),
('oberon', 'Oberon'),
('organic-fish-15-1-1', 'Organic Fish 15-1-1'),
('organic-soil-con', 'Organic Soil-Con'),
('outlook', 'Outlook'),
('overhaul', 'Overhaul'),
('p-26', 'P-26'),
('parallel', 'Parallel'),
('pilot-4e', 'Pilot 4E'),
('priaxor', 'Priaxor'),
('propaz', 'Propaz'),
('quilt-xcel', 'Quilt Xcel'),
('raindrops', 'Raindrops'),
('realize', 'Realize'),
('sanidae', 'Sanidae'),
('sodium-hyptochloride', 'Sodium Hyptochloride'),
('sodium-nitrate', 'Sodium Nitrate'),
('solubor', 'Solubor'),
('spe-120', 'SPE-120'),
('stalwart-c', 'Stalwart C'),
('sulfur', 'Sulfur'),
('thiosul', 'Thiosul'),
('top-flow-calcium', 'Top Flow Calcium'),
('tricor-df', 'Tricor DF'),
('trivapro', 'Trivapro'),
('tundra', 'Tundra'),
('warrier-seon', 'Warrier II Seon'),
('yuma', 'Yuma'),
('zicron-s', 'Zicron S'),
('zinc-10', 'Zinc 10%')


insert into dbo.ChemicalUnit(ChemicalUnitID, ChemicalUnitName, ChemicalUnitPluralName, ChemicalUnitLowercaseShortName)
values
(1, 'Pound', 'Pounds', 'lbs'),
(2, 'Gallon', 'Gallons', 'gal'),
(3, 'Ounce', 'Ounces', 'oz'),
(4, 'Pint', 'Pints', 'pints'),
(5, 'Pint/Acre', 'Pints/Acres', 'pints/acres'),
(6, 'Ton', 'Tons', 'tons')