{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger.fullname" . }}-qa-configmap
data:
  SECRET_PATH: "/app/secrets/zybachSwaggerSecrets"
  ASPNETCORE_ENVIRONMENT: "Staging"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
  INFLUXDB_URL: "https://us-west-2-1.aws.cloud2.influxdata.com"
  INFLUXDB_ORG: "GeoOptix"
  INFLUX_BUCKET: "tpnrd"
{{ end }}