{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "swagger.fullname" . }}-qa-configmap
data:
  SECRET_PATH: "/app/secrets/zybachSwaggerSecrets"
  DOCKER_BUILD_SOURCE: "."
  ASPNETCORE_ENVIRONMENT: "Staging"
  APPINSIGHTS_INSTRUMENTATIONKEY: "{{ .Values.global.env.appInsightsInstrumentationKey }}"
{{ end }}