version: '3.5'

services:
  zybach.api:
    build:
      dockerfile: Zybach.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - WEB_URL=${WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - PlatformLongName=${PlatformLongName}
      - LeadOrganizationLongName=${LeadOrganizationLongName}
      - LeadOrganizationHomeUrl=${LeadOrganizationHomeUrl}
      - LeadOrganizationEmail=${LeadOrganizationEmail}