version: '3.5'

services:
  zybach.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - KEYSTONE_HOST=${KEYSTONE_HOST}
      - DB_CONNECTION_STRING=${DB_CONNECTION_STRING}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SITKA_EMAIL_REDIRECT=${SITKA_EMAIL_REDIRECT}
      - DROOLTOOL_WEB_URL=${DROOLTOOL_WEB_URL}
      - SECRET_PATH=${SECRET_PATH}
      - KEYSTONE_REDIRECT_URL=${KEYSTONE_REDIRECT_URL}
      - KEYSTONE_AUTHORITY_URL=${KEYSTONE_AUTHORITY_URL}
      - GEOOPTIX_USERNAME=${GEOOPTIX_USERNAME}
      - GEOOPTIX_PASSWORD=${GEOOPTIX_PASSWORD}
      - GEOOPTIX_CLIENT_ID=${GEOOPTIX_CLIENT_ID}
      - GEOOPTIX_CLIENT_SECRET=${GEOOPTIX_CLIENT_SECRET}
      - GEOOPTIX_HOST_NAME=${GEOOPTIX_HOST_NAME}