version: '3.4'

services:
  zybachapi:
    image: zybachapi
    build: .
    environment: 
      - SOURCE_BUCKET=tpnrd
      - TS_NODE_PROJECT=/src/tsconfig.json
    secrets:
      - NODE_API_SECRETS
    ports:
      - 3000:3000
      - 9229:9229
    command: yarn debug
    volumes:
      - ./src:/src
secrets:
  NODE_API_SECRETS: 
    file: secrets.json
