const swaggerJsdoc = require('swagger-jsdoc');
const options = {
  // List of files to be processed.
  apis: ['./app_api/routes/index.js'],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  swaggerDefinition: {
    openapi:  '3.0.3',
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Zybach API',
      version: '0.0.1',
    },
    components: {
        securitySchemes: {
            bearerAuth: {
                type: 'http',
                scheme: 'bearer',
                bearerFormat: 'JWT'
            }
        }
    }
  },
};
const specs = swaggerJsdoc(options);

module.exports = specs;