const swaggerJsdoc = require('swagger-jsdoc');
const secrets = require('./secrets');
const options = {
  // List of files to be processed.
  apis: ['./app_api/routes/index.js'],
  // You can also set globs for your apis
  // e.g. './routes/*.js'
  swaggerDefinition: {
    openapi:  '3.0.3',
    info: {
      description: 'Test API with autogenerated swagger doc',
      swagger: '2.0',
      title: 'Zybach API',
      version: '0.0.2'
    },
    externalDocs: {
      description : "Documentation as raw JSON",
      url : `${secrets.WEB_SCHEME_AND_DOMAIN}/api-docs/swagger.json`
    },
    components: {
        securitySchemes: {
            bearerAuth: {
                type: 'apiKey',
                name: 'Authorization',
                in: 'header',
                scheme: 'bearer',
                bearerFormat: 'JWT'
            }
        }
    }
  },
};
const specs = swaggerJsdoc(options);

module.exports = specs;