SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[AgHubWellIrrigationUnit](
	[AgHubWellIrrigationUnitID] [int] IDENTITY(1,1) NOT NULL,
	[AgHubWellID] [int] NOT NULL,
	[IrrigationUnitGeometry] [geometry] NOT NULL,
 CONSTRAINT [PK_AgHubWellIrrigationUnit_AgHubWellIrrigationUnitID] PRIMARY KEY CLUSTERED 
(
	[AgHubWellIrrigationUnitID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_AgHubWellIrrigationUnit_AgHubWellID] UNIQUE NONCLUSTERED 
(
	[AgHubWellID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[AgHubWellIrrigationUnit]  WITH CHECK ADD  CONSTRAINT [FK_AgHubWellIrrigationUnit_AgHubWell_AgHubWellID] FOREIGN KEY([AgHubWellID])
REFERENCES [dbo].[AgHubWell] ([AgHubWellID])
GO
ALTER TABLE [dbo].[AgHubWellIrrigationUnit] CHECK CONSTRAINT [FK_AgHubWellIrrigationUnit_AgHubWell_AgHubWellID]