SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WellIrrigatedAcre](
	[WellIrrigatedAcreID] [int] IDENTITY(1,1) NOT NULL,
	[WellID] [int] NOT NULL,
	[IrrigationYear] [int] NOT NULL,
	[Acres] [float] NOT NULL,
 CONSTRAINT [PK_WellIrrigatedAcre_WellIrrigatedAcreID] PRIMARY KEY CLUSTERED 
(
	[WellIrrigatedAcreID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_WellIrrigatedAcre_WellID_IrrigationYear] UNIQUE NONCLUSTERED 
(
	[WellID] ASC,
	[IrrigationYear] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[WellIrrigatedAcre]  WITH CHECK ADD  CONSTRAINT [FK_WellIrrigatedAcre_Well_WellID] FOREIGN KEY([WellID])
REFERENCES [dbo].[Well] ([WellID])
GO
ALTER TABLE [dbo].[WellIrrigatedAcre] CHECK CONSTRAINT [FK_WellIrrigatedAcre_Well_WellID]