SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StreamFlowZone](
	[StreamFlowZoneID] [int] IDENTITY(1,1) NOT NULL,
	[StreamFlowZoneName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[StreamFlowZoneGeometry] [geometry] NOT NULL,
	[StreamFlowZoneArea] [float] NOT NULL,
 CONSTRAINT [PK_StreamFlowZone_StreamFlowZoneID] PRIMARY KEY CLUSTERED 
(
	[StreamFlowZoneID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_StreamFlowZone_StreamFlowZoneName] UNIQUE NONCLUSTERED 
(
	[StreamFlowZoneName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
