CREATE TABLE [dbo].[SensorType](
	[SensorTypeID] [int] NOT NULL,
	[SensorTypeName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[SensorTypeDisplayName] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ChartColor] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[AnomalousChartColor] [varchar](50) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[YAxisTitle] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[ReverseYAxisScale] [bit] NOT NULL,
 CONSTRAINT [PK_SensorType_SensorTypeID] PRIMARY KEY CLUSTERED 
(
	[SensorTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_SensorType_SensorTypeDisplayName] UNIQUE NONCLUSTERED 
(
	[SensorTypeDisplayName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_SensorType_SensorTypeName] UNIQUE NONCLUSTERED 
(
	[SensorTypeName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
