CREATE TABLE [dbo].[OpenETSync](
	[OpenETSyncID] [int] IDENTITY(1,1) NOT NULL,
	[OpenETDataTypeID] [int] NOT NULL,
	[Year] [int] NOT NULL,
	[Month] [int] NOT NULL,
	[FinalizeDate] [datetime] NULL,
 CONSTRAINT [PK_OpenET_OpenETSyncID] PRIMARY KEY CLUSTERED 
(
	[OpenETSyncID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_OpenETSync_Year_Month_OpenETDataTypeID] UNIQUE NONCLUSTERED 
(
	[Year] ASC,
	[Month] ASC,
	[OpenETDataTypeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[OpenETSync]  WITH CHECK ADD  CONSTRAINT [FK_OpenETSync_OpenETDataType_OpenETDataTypeID] FOREIGN KEY([OpenETDataTypeID])
REFERENCES [dbo].[OpenETDataType] ([OpenETDataTypeID])
GO
ALTER TABLE [dbo].[OpenETSync] CHECK CONSTRAINT [FK_OpenETSync_OpenETDataType_OpenETDataTypeID]