CREATE TABLE [dbo].[GeoOptixWellStaging](
	[GeoOptixWellStagingID] [int] IDENTITY(1,1) NOT NULL,
	[WellRegistrationID] [varchar](100) COLLATE SQL_Latin1_General_CP1_CI_AS NOT NULL,
	[WellGeometry] [geometry] NOT NULL,
 CONSTRAINT [PK_GeoOptixWellStaging_GeoOptixWellStagingID] PRIMARY KEY CLUSTERED 
(
	[GeoOptixWellStagingID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
