CREATE TABLE [dbo].[GeoOptixWell](
	[GeoOptixWellID] [int] IDENTITY(1,1) NOT NULL,
	[WellID] [int] NOT NULL,
	[GeoOptixWellGeometry] [geometry] NOT NULL,
 CONSTRAINT [PK_GeoOptixWell_GeoOptixWellID] PRIMARY KEY CLUSTERED 
(
	[GeoOptixWellID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [AK_GeoOptixWell_WellID] UNIQUE NONCLUSTERED 
(
	[WellID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
ALTER TABLE [dbo].[GeoOptixWell]  WITH CHECK ADD  CONSTRAINT [FK_GeoOptixWell_Well_WellID] FOREIGN KEY([WellID])
REFERENCES [dbo].[Well] ([WellID])
GO
ALTER TABLE [dbo].[GeoOptixWell] CHECK CONSTRAINT [FK_GeoOptixWell_Well_WellID]