{{ if eq .Values.global.env.name "qa" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "web.fullname" . }}-qa-configmap
data:
  ASPNETCORE_ENVIRONMENT: "Staging"
  production: "false"
  staging: "true"
  dev: "false"
  mainAppApiUrl: "https://{{ .Values.global.domains.api }}"
  createAccountRedirectUrl: "https://{{ .Values.global.domains.web }}/create-user-callback"
  keystoneSupportBaseUrl: "https://identity-qa.sitkatech.com/Authentication"
  geoserverMapServiceUrl: "https://{{ .Values.global.domains.geoserver }}/geoserver/Zybach"
  keystone_clientId: "Zybach"
  keystone_issuer: "https://identity-qa.sitkatech.com"
  keystone_redirectUriRelative: "/signin-oidc"
  keystone_scope: "openid profile offline_access keystone"
  keystone_sessionCheckEnabled: "false"
  keystone_logoutUrl: "https://identity-qa.sitkatech.com/account/logout"
  keystone_postLogoutRedirectUri: "/"
  keystone_waitForTokenInMsec: "500"
  keystone_responseType: "code"
  keystone_disablePKCE: "false"
  AllowOpenETSync: "true"
  GeooptixWebUrl: "https://tpnrd.geooptix.com"
  MapQuestApiUrl: "https://open.mapquestapi.com/nominatim/v1/search.php?key=gAtuAvFkArwZH61P1UVcRXseleJWEB7r"
  GETEnvironmentUrl: "https://getqa.azurewebsites.net"
{{ end }}  