global:
  env:
    name: "qa"
    dbServer: "db-server.database.windows.net"
    databaseName: "ZybachDB"
    sqlUsername: "SqlAdministrator"
    appInsightsInstrumentationKey: "00000000-0000-0000-0000-000000000000"
    getApiSubscriptionKey: "some-guid"
  domains:
    api: "internalapi-zybach.aks-qa.sitkatech.com"
    web: "zybach.aks-qa.sitkatech.com"
    swaggerApi: "api-zybach.aks-qa.sitkatech.com"
  secrets:
    apiKeyValue: "apiKeyValue"
    apiSqlPassword: "passwordhere"
    hangfirePassword: "passwordhere"
    openETShapefilePath: "openETShapefilePath"
    openETApiKey: "openETApiKey"
    sendGridApiKey: "sendgridapikeyhere"
    zybachApiKey: "zybachApiKey"
    agHubApiKey: "agHubApiKey"
    geoOptixApiKey: "geoOptixApiKey"
    influxDBToken: "influxDBToken"
    influxDBOrg: "influxDBOrg"
    influxBucket: "influxBucket"
    zybachClientID: "zybachClientID"
    zybachClientSecret: "zybachClientSecret"

api:
  replicaCount: 1
  image:
    repository: esacontainers.azurecr.io/zybach/api
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "1G"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "300"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

swagger:
  replicaCount: 1
  image:
    repository: esacontainers.azurecr.io/zybach/swagger
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "256Mi"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "300"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}
  
web:
  replicaCount: 1
  image:
    repository: esacontainers.azurecr.io/zybach/web
    pullPolicy: Always
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "256Mi"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      appgw.ingress.kubernetes.io/request-timeout: "300"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

geoserver:
  replicaCount: 1
  image:
    repository: kartoza/geoserver
    pullPolicy: Always
    tag: "2.16.2"
    # Overrides the image tag whose default is the chart appVersion.
  nameOverride: ""
  fullnameOverride: ""
  namespace: h2o
  resources: 
    requests:
      memory: "1G"
  serviceAccount:
    # Specifies whether a service account should be created
    create: true
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  podAnnotations: {}
  podSecurityContext: {}
    # fsGroup: 2000
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  service:
    type: ClusterIP
    port: 80
  ingress:
    enabled: true
    className: ""
    annotations:
      kubernetes.io/ingress.class: azure/application-gateway
      cert-manager.io/cluster-issuer: letsencrypt
      acme.cert-manager.io/http01-edit-in-place: "true"
      appgw.ingress.kubernetes.io/ssl-redirect: "true"
      cert-manager.io/issue-temporary-certificate: "true"
      appgw.ingress.kubernetes.io/connection-draining: "true"
      appgw.ingress.kubernetes.io/connection-draining-timeout: "30"
  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    # targetMemoryUtilizationPercentage: 80
  nodeSelector: 
    agentpool: appnodepool
  tolerations: []
  affinity: {}

rabbitmq:
  auth:
    username: "rabbitUser"
    password: "rabbitPass"
    erlangCookie: "6085e2412b6fa88647466c6a81c0cea0"