version: '3.4'

services:
  chemigation-sync:
    image: chemigation-sync
    build: .
    environment: 
      - DEBUG=true
      - GEOOPTIX_BASE_URL=https://tpnrd.api-qa.geooptix.com
      - TS_NODE_PROJECT=/src/tsconfig.json
    secrets:
      - Chemigation_Sync_Secret
    ports:
      - 3001:3001
      - 9230:9230
    command: yarn start-dev
    # command: crond -f -l 8
secrets:
  Chemigation_Sync_Secret: 
    file: secrets.json
